CREATE TABLE  USER (
  `ID` bigint(20) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `NAME` varchar(50) DEFAULT NULL COMMENT '姓名',
  `PWD` varchar(50) NOT NULL COMMENT '密码',
  `SEX` varchar(3) DEFAULT '' COMMENT '性别',
  `MOBILE` varchar(20) DEFAULT NULL COMMENT '手机',
  `EMAIL` varchar(150) DEFAULT NULL COMMENT 'EMAIL',
  `AVATAR` varchar(20) DEFAULT NULL COMMENT '昵称',
  `status` varchar(500) DEFAULT 'Y' COMMENT '有效状态'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED COMMENT='用户表';